name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Enable corepack
      run: corepack enable
    - name: Install dependencies
      run: yarn --immutable
