name: Review PR
run-name: ${{ github.actor }} is reviewing the PR 🚀
on:
  pull_request:
    branches:
      - main

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn --immutable

  check-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: yarn lint
